### ISSUE TITLE
movie issue

### ISSUE THREAD

**Issue by BrothaGithubber** [m-patino/fancaps-downloader#6]
https://fancaps.net/movies/MovieImages.php?name=Black_Clover_Sword_of_the_Wizard_King_2023 crawling started:
        "movie" url detected
Traceback (most recent call last):
  File "D:\AI ART\fancaps-downloader-main\fancaps-downloader.py", line 15, in <module>
    links = crawler.crawl(args.url)
  File "D:\AI ART\fancaps-downloader-main\scraper\crawler.py", line 22, in crawl
    output = [crawler.crawl(url)]
  File "D:\AI ART\fancaps-downloader-main\scraper\crawlers\movie_crawler.py", line 13, in crawl
    subfolder = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
'movieid' is not recognized as an internal or external command,
operable program or batch file.

**Comment by m-patino** [comment]
Hi @BrothaGithubber,

Sorry for this error, i need to add a better error handling.
Try with this command: 
```
python fancaps-downloader.py "https://fancaps.net/movies/MovieImages.php?name=Black_Clover_Sword_of_the_Wizard_King_2023&movieid=4087"
```
The error come with `&` in args. I will see if a can fix that later or add an error (because this is a special character)

Have a nice day

**Comment by BrothaGithubber** [comment]
thank you very much
